### FA19-BCS-034

### Abdul Rehman

### G2

In [1]:
import warnings
warnings.filterwarnings('ignore') # setting ignore as a parameter

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [2]:
# Create sample set of documents
S1 ="sunshine state enjoy sunshine"
S2="brown fox jump high, brown fox run"
S3="sunshine state fox run fast"

docs = np.array([S1,S2,S3])

In [3]:
#print docs
docs

array(['sunshine state enjoy sunshine',
       'brown fox jump high, brown fox run',
       'sunshine state fox run fast'], dtype='<U34')

# Question 1

In [4]:
vectorizer = CountVectorizer()

In [5]:
# Get unique words / tokens found in all the documents. The unique words / tokens represents
# the features
bag = vectorizer.fit_transform(docs)
print(vectorizer.get_feature_names())


['brown', 'enjoy', 'fast', 'fox', 'high', 'jump', 'run', 'state', 'sunshine']


In [6]:
# Associate the indices with each unique word
print(vectorizer.vocabulary_)

{'sunshine': 8, 'state': 7, 'enjoy': 1, 'brown': 0, 'fox': 3, 'jump': 5, 'high': 4, 'run': 6, 'fast': 2}


In [7]:
print(bag.toarray())

[[0 1 0 0 0 0 0 1 2]
 [2 0 0 2 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 1]]


#### Bag of words

In [8]:
BOW = pd.DataFrame(bag.toarray(),index=['S1','S2','S3'],columns = vectorizer.get_feature_names())
BOW

brown  enjoy  fast  fox  high  jump  run  state  sunshine
S1      0      1     0    0     0     0    0      1         2
S2      2      0     0    2     1     1    1      0         0
S3      0      0     1    1     0     0    1      1         1

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer,TfidfTransformer

In [10]:
#calculating the term frequency
tfidf_vectorizer = TfidfVectorizer(use_idf=False)
tf = tfidf_vectorizer.fit_transform(docs)
tf

<3x9 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

#### Term Frequency

In [11]:
tf_pd = pd.DataFrame(tf.toarray(),index=['S1','S2','S3'],columns = vectorizer.get_feature_names())
tf_pd

brown     enjoy      fast       fox      high      jump       run  \
S1  0.000000  0.408248  0.000000  0.000000  0.000000  0.000000  0.000000   
S2  0.603023  0.000000  0.000000  0.603023  0.301511  0.301511  0.301511   
S3  0.000000  0.000000  0.447214  0.447214  0.000000  0.000000  0.447214   

       state  sunshine  
S1  0.408248  0.816497  
S2  0.000000  0.000000  
S3  0.447214  0.447214

In [12]:
tfidf_vectorizers = TfidfVectorizer(use_idf=True)
tfidf = tfidf_vectorizers.fit_transform(docs)

#### IDF

In [13]:
#print idf
idf = pd.DataFrame({'feature_name':vectorizer.get_feature_names(), 'idf_weights':tfidf_vectorizers.idf_})
idf

feature_name  idf_weights
0        brown     1.693147
1        enjoy     1.693147
2         fast     1.693147
3          fox     1.287682
4         high     1.693147
5         jump     1.693147
6          run     1.287682
7        state     1.287682
8     sunshine     1.287682

#### TF-IDF

In [14]:
#print tfidf
tfidf_pd = pd.DataFrame(tfidf.toarray(),index=['S1','S2','S3'],columns = vectorizer.get_feature_names())
tfidf_pd

brown    enjoy      fast       fox      high      jump       run  \
S1  0.000000  0.50689  0.000000  0.000000  0.000000  0.000000  0.000000   
S2  0.670703  0.00000  0.000000  0.510087  0.335352  0.335352  0.255044   
S3  0.000000  0.00000  0.549351  0.417796  0.000000  0.000000  0.417796   

       state  sunshine  
S1  0.385503  0.771006  
S2  0.000000  0.000000  
S3  0.417796  0.417796

# Question 2

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

#### Taking TF vector

In [16]:
get = tf.toarray()

In [17]:
get

array([[0.        , 0.40824829, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40824829, 0.81649658],
       [0.60302269, 0.        , 0.        , 0.60302269, 0.30151134,
        0.30151134, 0.30151134, 0.        , 0.        ],
       [0.        , 0.        , 0.4472136 , 0.4472136 , 0.        ,
        0.        , 0.4472136 , 0.4472136 , 0.4472136 ]])

### Cosine Similarity Between S1 and S3

In [18]:
print(cosine_similarity([get[0]], [get[2]]))


[[0.54772256]]
